In [6]:
 print("Hello World")

Hello World


In [11]:
!pip install numpy

     |████████████████████████████████| 14.5 MB 3.0 MB/s eta 0:00:01    |████████████▊                   | 5.8 MB 3.0 MB/s eta 0:00:03


In [12]:
import numpy as np

In [14]:
!pip install pandas

     |████████████████████████████████| 9.5 MB 3.4 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 47.7 MB/s eta 0:00:01


In [15]:
import numpy as np
import numpy.linalg as npl
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell

In [16]:
InteractiveShell.ast_node_interactivity = "all"

In [17]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,1])
try:
    npl.solve(mat,sol)
except:
    print(np.hstack([mat,sol]))
    print("Not solveable. Adding rows 1 and 2 contradicts row 3.")

[[ 1  1  1  3]
 [ 1 -1  2  2]
 [ 2  0  3  1]]
Not solveable. Adding rows 1 and 2 contradicts row 3.


In [18]:
mat

array([[ 1,  1,  1],
       [ 1, -1,  2],
       [ 2,  0,  3]])