In [1]:
 print("Hello World")

Hello World


In [2]:
!pip install numpy

     |████████████████████████████████| 14.5 MB 3.0 MB/s eta 0:00:01    |█▋                              | 716 kB 3.0 MB/s eta 0:00:05


In [3]:
import numpy as np

In [4]:
!pip install pandas

     |████████████████████████████████| 9.5 MB 3.0 MB/s eta 0:00:01     |█████████████████▎              | 5.1 MB 3.0 MB/s eta 0:00:02
     |████████████████████████████████| 510 kB 51.4 MB/s eta 0:00:01


In [2]:
import numpy as np
import numpy.linalg as npl
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell

In [3]:
InteractiveShell.ast_node_interactivity = "all"

In [10]:
mat

array([[ 1,  1,  1],
       [ 1, -1,  2],
       [ 2,  0,  3]])

In [11]:
import numpy as np

In [12]:
mat

array([[ 1,  1,  1],
       [ 1, -1,  2],
       [ 2,  0,  3]])

# Chapter 02. Linear Algebra
2.1 Systems of Linear Equations
Example 2.2

# Ax = b ( we are trying to solve this linear system of equations)

In [19]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,1])
try:
    npl.solve(mat,sol)
except:
    print(np.hstack([mat,sol]))
    print("Not solveable. Adding rows 1 and 2 contradicts row 3.")

[[ 1  1  1  3]
 [ 1 -1  2  2]
 [ 2  0  3  1]]
Not solveable. Adding rows 1 and 2 contradicts row 3.


In [ ]:
mat = np.vstack([[1,1,1],[1,-1,2],[0,1,1]])
sol = np.vstack([3,2,2])
print(np.hstack([mat,sol]))
print("Solveable. Adding row 1 and 3 reveals x = 1, which fits with all rows.")
npl.solve(mat,sol)

In [ ]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,5])
print(np.hstack([mat,sol]))
npl.lstsq(mat,sol)[3] #Solution of coefficients multiplied with any # in R. I.e. Infinity of R solutions.

# numpy.linalg.lstsq(a, b, rcond='warn')[source]¶
# Return the least-squares solution to a linear matrix equation

In general, for a real-valued system of linear equations we obtain either
no, exactly one, or infinitely many solutions. Linear regression (Chapter 9)
solves a version of Example 2.1 when we cannot solve the system of linear
equations.

Computes the vector x that approximatively solves the equation a @ x = b. The equation may be under-, well-, or over-determined (i.e., the number of linearly independent rows of a can be less than, equal to, or greater than its number of linearly independent columns). If a is square and of full rank, then x (but for round-off error) is the “exact” solution of the equation. Else, x minimizes the Euclidean 2-norm || b - a x ||.

Figure 2.3¶
The solution space of a system of two linear equations with two variables can be geometrically interepreted as the interesection of two lines. Every linear equation represents a line.

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
vals = np.linspace(-10,10,10000)

In [ ]:
print(vals)

In [ ]:

plt.rcParams["figure.figsize"] = (5,5)

In [ ]:
eq0 = lambda x1: (5-4*x1)/4 # 4x1+4x2 = 5
y0 = eq0(vals)

eq1 = lambda x1: (1-2*x1)/-4 # 2x1-4x2 = 1
y1 = eq1(vals)

plt.plot(vals,y0,c="blue")
plt.plot(vals,y1,c="red")
idx = np.argwhere(np.diff(np.sign(y0 - y1))).flatten() # finds the intersection between two graphs
plt.plot(vals[idx],y0[idx],'ko')
plt.legend(["4$x_1$+4$x_2$ = 5","2$x_1$-4$x_2$ = 1",str(np.round(vals[idx],3)) + str(np.round(y0[idx],3))]);

In [ ]:
 print("Hello World")